[versions]
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"
jline = "3.25.1"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
mordant = "com.github.ajalt.mordant:mordant:2.3.0"
clikt = "com.github.ajalt.clikt:clikt:4.2.2"
jline-reader = { module = "org.jline:jline-reader", version.ref = "jline" }
jline-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "jline" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
buildconfig = "com.github.gmazzo.buildconfig:5.3.5"